
/* groovylint-disable-next-line CompileStatic */
pipeline {
    agent {
        label 'slave'
    }

    stages {
        stage('Git Clone') {
            steps {
                git branch: 'main', url: 'https://github.com/NextGen20/Main-Project.git'
            }
        }

        stage('Build & Run Image') {
            steps {
                sh 'sudo docker build -t flaskproject/myproject:latest ./first-app'
                sh 'sudo docker run --name flaskapp1 -d -p 5000:5000 flaskproject/myproject:latest'
            }
        }
        stage('Test-App') {
            steps {
                dir('first-app/test_app') {
                    sh 'pytest test_app.py'
                }
            }
        }
    }

    post {
        always {
            sh 'sudo docker stop $(sudo docker ps -aq)'
            sh 'sudo docker rm $(sudo docker ps -aq)'
        }
    }
}
