pipeline {
    agent { 
        node { 
            label 'slave'
        } 
    }

        stage('Deploy to Kubernetes') {
            steps {
                sh 'kubectl apply -f eks-flask-deployment/flask-deployment.yaml'
                sh 'kubectl apply -f eks-flask-deployment/flask-service.yaml'
            }
        }
    }

