pipeline {
    agent { 
        node { 
            label 'slave'
        } 
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                sh 'kubectl apply -f flask-deployment.yaml'
                sh 'kubectl apply -f flask-service.yaml'
            }
        }
    }
}
